module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  ignorePatterns: [
    'dist',
    'bin',
    'node_modules',
    '.nuxt',
    'output',
    'coverage',
    'public',
    'temp',
    'packages-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
    '__snapshots__',
    '!.vitepress',
    '!.vscode',
    'LICENSE*',
    'CHANGELOG*',
  ],
  extends: [
    './antfu.js',
    './eslint.js',
    './eslintComments.js',
    './import.js',
    './jsdoc.js',
    './jsonc.js',
    './markdown.js',
    './sonarjs.js',
    './typescript.js',
    './unicorn.js',
    './vitest.js',
    './vue.js',
    './yaml.js',
  ],
}
