import { expect, it } from 'vitest'
import { isStringBitcoinAddress, isStringDiscordUsername, isStringEmail, isStringEmoji, isStringFirestoreId, isStringIpv4, isStringIpv6, isStringJwt, isStringLatLong, isStringMac, isStringMatching, isStringPort, isStringSemver, isStringSlug, isStringTimestamp, isStringUrl, isStringUuid } from './isStringMatching'

it('checks if value matches the specified regex', () => {
  expect(isStringMatching('Hello World!', /hello/)).toEqual(false)
  expect(isStringMatching('Hello World!', /hello/i)).toEqual(true)
})

it('should return true for emojis', () => {
  expect(isStringEmoji('\u00A9')).toEqual(true)
  expect(isStringEmoji('\u00AE')).toEqual(true)
  expect(isStringEmoji('\u2000')).toEqual(true)
  expect(isStringEmoji('\u3300')).toEqual(true)
  expect(isStringEmoji('\uD83C\uD000')).toEqual(true)
  expect(isStringEmoji('\uD83C\uDFFF')).toEqual(true)
  expect(isStringEmoji('\uD83D\uD000')).toEqual(true)
  expect(isStringEmoji('\uD83D\uDFFF')).toEqual(true)
  expect(isStringEmoji('\uD83E\uD000')).toEqual(true)
  expect(isStringEmoji('\uD83E\uDFFF')).toEqual(true)
  expect(isStringEmoji('A')).toEqual(false)
  expect(isStringEmoji('*')).toEqual(false)
  expect(isStringEmoji('\n')).toEqual(false)
  expect(isStringEmoji('\r')).toEqual(false)
  expect(isStringEmoji('\t')).toEqual(false)
  expect(isStringEmoji(' ')).toEqual(false)
  expect(isStringEmoji('\uD83C')).toEqual(false)
  expect(isStringEmoji('\uD83D')).toEqual(false)
  expect(isStringEmoji('\uD83E')).toEqual(false)
})

it('checks if string matches a slug', () => {
  expect(isStringSlug('foo')).toEqual(true)
  expect(isStringSlug('foo-bar')).toEqual(true)
  expect(isStringSlug('foo-bar-baz')).toEqual(true)
  expect(isStringSlug('5')).toEqual(true)
  expect(isStringSlug('5-5')).toEqual(true)
  expect(isStringSlug('5-5-5')).toEqual(true)
  expect(isStringSlug('foo.bar')).toEqual(false)
  expect(isStringSlug('foo@bar')).toEqual(false)
})

it('checks if string matches an email', () => {
  expect(isStringEmail('foo@bar.com')).toEqual(true)
  expect(isStringEmail('foo.bar@baz.com')).toEqual(true)
  expect(isStringEmail('foo+bar@baz.com')).toEqual(true)
  expect(isStringEmail('foo@bar.co.uk')).toEqual(true)
  expect(isStringEmail('foo@bar.io')).toEqual(true)
  expect(isStringEmail('foo@bar.museum')).toEqual(true)
  expect(isStringEmail('foo@baz')).toEqual(false)
  expect(isStringEmail('foo@baz.com')).toEqual(true)
  expect(isStringEmail('foo@baz.com.co')).toEqual(true)
  expect(isStringEmail('foo@baz.net')).toEqual(true)
  expect(isStringEmail('foo@baz.org')).toEqual(true)
  expect(isStringEmail('foobar')).toEqual(false)
  expect(isStringEmail('foo@')).toEqual(false)
  expect(isStringEmail('@bar')).toEqual(false)
  expect(isStringEmail('foo.bar')).toEqual(false)
  expect(isStringEmail('.foo.bar')).toEqual(false)
  expect(isStringEmail('foo+bar')).toEqual(false)
  expect(isStringEmail('foo@+bar')).toEqual(false)
  expect(isStringEmail('foo@bar+')).toEqual(false)
})

it('should return true if string is a URL', () => {
  expect(isStringUrl('http://foo.com')).toEqual(true)
  expect(isStringUrl('https://foo.com')).toEqual(true)
  expect(isStringUrl('http://foo.com:80')).toEqual(true)
  expect(isStringUrl('http://foo.com/bar')).toEqual(true)
  expect(isStringUrl('http://foo.com/bar?baz=qux')).toEqual(true)
  expect(isStringUrl('http://foo.com/bar?baz=qux#quux')).toEqual(true)
  expect(isStringUrl('foo')).toEqual(false)
  expect(isStringUrl('Bar')).toEqual(false)
  expect(isStringUrl('http://')).toEqual(false)
  expect(isStringUrl('http://foo')).toEqual(true)
  expect(isStringUrl('https://foo')).toEqual(true)
  expect(isStringUrl('http://foo:80')).toEqual(true)
  expect(isStringUrl('http://foo.com:8')).toEqual(true)
  expect(isStringUrl('ftp://foo.com')).toEqual(true)
  expect(isStringUrl('http:foo.com')).toEqual(true)
  expect(isStringUrl('http:/foo.com')).toEqual(false)
  expect(isStringUrl('http:///foo.com')).toEqual(false)
  expect(isStringUrl('http://?foo.com')).toEqual(false)
  expect(isStringUrl('http://#foo.com')).toEqual(false)
  expect(isStringUrl('http://foo.com?')).toEqual(true)
  expect(isStringUrl('http://foo.com#')).toEqual(true)
  expect(isStringUrl('http://foo.com/?')).toEqual(true)
  expect(isStringUrl('http://foo.com/#')).toEqual(true)
  expect(isStringUrl('http://foo.com?#')).toEqual(true)
  expect(isStringUrl('http://foo.com??')).toEqual(true)
  expect(isStringUrl('http://foo.com##')).toEqual(true)
})

it('should return true for valid MAC addresses', () => {
  expect(isStringMac('01:02:03:04:05:06')).toEqual(true)
  expect(isStringMac('01:AB:CD:EF:AB:CD')).toEqual(true)
  expect(isStringMac('AB:CD:EF:AB:CD:EF')).toEqual(true)
  expect(isStringMac('01:ab:cd:ef:ab:cd')).toEqual(true)
  expect(isStringMac('ab:cd:ef:ab:cd:ef')).toEqual(true)
  expect(isStringMac('01:02:03:04:05:6')).toEqual(false)
  expect(isStringMac('01:02:03:04:05')).toEqual(false)
  expect(isStringMac('01:02:03:04:05:00:00')).toEqual(false)
  expect(isStringMac('01-02-03-04-05-06')).toEqual(false)
  expect(isStringMac('1:2:3:4:5:6')).toEqual(false)
  expect(isStringMac('01.02.03.04.05.06')).toEqual(false)
  expect(isStringMac('0102.0304.0506')).toEqual(false)
  expect(isStringMac('G:H:I:J:K:L')).toEqual(false)
})

it('should return true for valid UUID', () => {
  expect(isStringUuid('123e4567-e89b-12d3-a456-426655440002')).toEqual(true)
  expect(isStringUuid('12345678-1234-5678-1234-567812345678')).toEqual(false)
  expect(isStringUuid('12345')).toEqual(false)
  expect(isStringUuid('12345678-1234-5678-1234-567812345678')).toEqual(false)
  expect(isStringUuid('abcdefgh-ijkl-mnop-qrst-uvwxyzabcdef')).toEqual(false)
})

it('should return true if string is valid IPv4', () => {
  expect(isStringIpv4('1.1.1.1')).toEqual(true)
  expect(isStringIpv4('255.255.255.255')).toEqual(true)
  expect(isStringIpv4('192.168.0.1')).toEqual(true)
  expect(isStringIpv4('1234.1.1.1')).toEqual(false)
  expect(isStringIpv4('999.255.255.255')).toEqual(false)
  expect(isStringIpv4('0.0.0.0')).toEqual(true)
  expect(isStringIpv4('255.255.255.256')).toEqual(false)
  expect(isStringIpv4('255.255.255')).toEqual(false)
  expect(isStringIpv4('255.255')).toEqual(false)
  expect(isStringIpv4('255')).toEqual(false)
  expect(isStringIpv4('0.0.0.0.0')).toEqual(false)
  expect(isStringIpv4('1.2.3.4.5')).toEqual(false)
})

it('should match IPv6 addresses', () => {
  expect(isStringIpv6('::')).toEqual(true)
  expect(isStringIpv6('::1')).toEqual(true)
  expect(isStringIpv6('1::')).toEqual(true)
  expect(isStringIpv6('fe80::ae21:afff:feea:8e4a')).toEqual(true)
  expect(isStringIpv6('2001:0db8:85a3:0000:0000:8a2e:0370:7334')).toEqual(true)
  expect(isStringIpv6('0.0.0.0')).toEqual(false)
  expect(isStringIpv6('255.255.255.255')).toEqual(false)
  expect(isStringIpv6('foo')).toEqual(false)
})

it('should check if a string matches port numbers', () => {
  expect(isStringPort('0')).toEqual(true)
  expect(isStringPort('80')).toEqual(true)
  expect(isStringPort('443')).toEqual(true)
  expect(isStringPort('3000')).toEqual(true)
  expect(isStringPort('8080')).toEqual(true)
  expect(isStringPort('65535')).toEqual(true)
  expect(isStringPort('-1')).toEqual(false)
  expect(isStringPort('65536')).toEqual(false)
  expect(isStringPort('1.2.3.4')).toEqual(false)
  expect(isStringPort('foo')).toEqual(false)
  expect(isStringPort('8080/tcp')).toEqual(false)
})

it('should return true when string matches Semantic Versioning', () => {
  expect(isStringSemver('0.0.4')).toEqual(true)
  expect(isStringSemver('1.2.3')).toEqual(true)
  expect(isStringSemver('10.20.30')).toEqual(true)
  expect(isStringSemver('1.1.2-alpha.1')).toEqual(true)
  expect(isStringSemver('1.2.3-beta.2')).toEqual(true)
  expect(isStringSemver('1.0.0-rc.3')).toEqual(true)
  expect(isStringSemver('1.2.3-alpha.1.2.3-beta.2.3.4-rc.3.2.1')).toEqual(true)
  expect(isStringSemver('0.0.4-alpha')).toEqual(true)
  expect(isStringSemver('aloha')).toEqual(false)
})

it('should match correct latitude longitude strings', () => {
  expect(isStringLatLong('0.0,0.0')).toEqual(true)
  expect(isStringLatLong('0.0,0.0,0.0')).toEqual(false)
  expect(isStringLatLong('-90.0,-180.0')).toEqual(true)
  expect(isStringLatLong('-90.0,-180.0,0.0')).toEqual(false)
  expect(isStringLatLong('90.0,180.0')).toEqual(true)
  expect(isStringLatLong('90.0,180.0,0.0')).toEqual(false)
  expect(isStringLatLong('a')).toEqual(false)
  expect(isStringLatLong('abc')).toEqual(false)
  expect(isStringLatLong('1234')).toEqual(false)
})

it('should return true if string matches ISO 8601', () => {
  expect(isStringTimestamp('1994-11-05T13:15:30Z')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T08:15:30-05:00')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T08:15:30+05:00')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T08:15:30.45')).toEqual(false)
  expect(isStringTimestamp('1994-11-05T08:15:30.45+05:00')).toEqual(false)
  expect(isStringTimestamp('1994-11-05')).toEqual(true)
  expect(isStringTimestamp('19941105T131530Z')).toEqual(true)
  expect(isStringTimestamp('19941105T131530.45')).toEqual(false)
  expect(isStringTimestamp('19941105T131530.45+0500')).toEqual(false)
  expect(isStringTimestamp('1994-W48-5')).toEqual(true)
  expect(isStringTimestamp('1994W485')).toEqual(true)
  expect(isStringTimestamp('1994-135')).toEqual(true)
  expect(isStringTimestamp('19941350')).toEqual(false)
  expect(isStringTimestamp('1994-W15-5T13:15:30Z')).toEqual(true)
  expect(isStringTimestamp('1994W155T131530Z')).toEqual(true)
  expect(isStringTimestamp('1994-W15-5')).toEqual(true)
  expect(isStringTimestamp('1994W155')).toEqual(true)
  expect(isStringTimestamp('1994-05')).toEqual(true)
  expect(isStringTimestamp('199405')).toEqual(true)
  expect(isStringTimestamp('1994-05-05T08:15:30-05:00')).toEqual(true)
  expect(isStringTimestamp('19940505T131530Z')).toEqual(true)
  expect(isStringTimestamp('1994-05-05')).toEqual(true)
  expect(isStringTimestamp('19940505')).toEqual(true)
  expect(isStringTimestamp('1994137T131530Z')).toEqual(false)
  expect(isStringTimestamp('1994137')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T13:15:30')).toEqual(true)
  expect(isStringTimestamp('1994-11-05 08:15:30-05:00')).toEqual(false)
  expect(isStringTimestamp('1994-11-05T081530+05:00')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T08:15:30+05')).toEqual(true)
  expect(isStringTimestamp('1994-11-05T08:15:30.045+05:00')).toEqual(true)
  expect(isStringTimestamp('1994-11-05-')).toEqual(false)
  expect(isStringTimestamp('19941105T131530+05:00')).toEqual(true)
  expect(isStringTimestamp('19941105T131530.45+05')).toEqual(false)
  expect(isStringTimestamp('19941105T131530.045+0500')).toEqual(true)
  expect(isStringTimestamp('1994-W48')).toEqual(true)
  expect(isStringTimestamp('1994W48')).toEqual(true)
  expect(isStringTimestamp('1994W48-5')).toEqual(true)
  expect(isStringTimestamp('1994W485-')).toEqual(false)
  expect(isStringTimestamp('1994-135T')).toEqual(false)
  expect(isStringTimestamp('1994135T')).toEqual(false)
  expect(isStringTimestamp('19941350T')).toEqual(false)
  expect(isStringTimestamp('1994-W15')).toEqual(true)
  expect(isStringTimestamp('1994W15')).toEqual(true)
  expect(isStringTimestamp('1994W15-5T13:15:30Z')).toEqual(true)
  expect(isStringTimestamp('1994W15-5T131530Z')).toEqual(true)
  expect(isStringTimestamp('1994W155T131530Z-')).toEqual(false)
  expect(isStringTimestamp('1994W155-')).toEqual(false)
  expect(isStringTimestamp('1994-05-')).toEqual(false)
  expect(isStringTimestamp('199405-')).toEqual(false)
  expect(isStringTimestamp('19940505T08:15:30-05:00')).toEqual(true)
  expect(isStringTimestamp('19940505T081530-05:00')).toEqual(true)
  expect(isStringTimestamp('19940505081530-05:00')).toEqual(false)
  expect(isStringTimestamp('19940505T081530Z-05:00')).toEqual(false)
  expect(isStringTimestamp('19940505-')).toEqual(false)
  expect(isStringTimestamp('1994137T131530+05:00')).toEqual(false)
  expect(isStringTimestamp('19941370T131530Z')).toEqual(false)
  expect(isStringTimestamp('19941370T131530Z-')).toEqual(false)
  expect(isStringTimestamp('19941370-')).toEqual(false)
})

it('should match Firestore ids', () => {
  expect(isStringFirestoreId('aBcDeFgHiJkLmNoPqRsTuVwXyZ')).toEqual(true)
  expect(isStringFirestoreId('AbCdEfGhIjKlMnOpQrStUvWxYz')).toEqual(true)
  expect(isStringFirestoreId('1234567890')).toEqual(true)
  expect(isStringFirestoreId('ABCDEFGHIJKLMNOPQRSTUVWXYZ')).toEqual(true)
  expect(isStringFirestoreId('abcdefghijklmnopqrstuvwxyz')).toEqual(true)
  expect(isStringFirestoreId('-_.~')).toEqual(true)
  expect(isStringFirestoreId('.aBcDeFgHiJkLmNoPqRsTuVwXyZ')).toEqual(true)
  expect(isStringFirestoreId('AbCdEfGhIjKlMnOpQrStUvWxYz.')).toEqual(true)
  expect(isStringFirestoreId('..')).toEqual(false)
  expect(isStringFirestoreId('__AbCdEfGhIjKlMnOpQrStUvWxYz__')).toEqual(false)
  expect(isStringFirestoreId('AbCdEfGhIjKlMnOpQrStUvWxYz/foo')).toEqual(false)
  expect(isStringFirestoreId('AbCdEfGhIjKlMnOpQrStUvWxYz/')).toEqual(false)
})

it('should match Discord usernames', () => {
  expect(isStringDiscordUsername('foo')).toEqual(false)
  expect(isStringDiscordUsername('foo#1234')).toEqual(true)
})

it('should match Bitcoin addresses', () => {
  expect(isStringBitcoinAddress('14B8F894a0A39F395F04c5336E5D7A1C97D790F4')).toEqual(true)
  expect(isStringBitcoinAddress('3E7T3uTtV3a5DDxr3E3UqCtR3E3E3E3E3E')).toEqual(true)
  expect(isStringBitcoinAddress('bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq')).toEqual(true)
  expect(isStringBitcoinAddress('bc1qc7slrfxkknqcq2jevvvkdgvrt8080852dfjewde450xdlk4ugp7szw5tk9')).toEqual(false)
  expect(isStringBitcoinAddress('14B8F894a0A39F395F04c5336E5D7A1C97D790F4.')).toEqual(false)
  expect(isStringBitcoinAddress('3E7T3uTtV3a5DDxr3E3UqCtR3E3E3E3E3E.')).toEqual(false)
  expect(isStringBitcoinAddress('3E7T3uTtV3a5DDxr3E3UqCtR3E3E3E3E3E/')).toEqual(false)
  expect(isStringBitcoinAddress('bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq/')).toEqual(false)
  expect(isStringBitcoinAddress('bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq/foo')).toEqual(false)
})

it('should return true when string matches JSON Web Token', () => {
  expect(isStringJwt('eyJhbGciOiJIUz.eyJzdWIiOiIxMjM0NTY3O.SflKxwRJSM6POk6yJV_adQssw5c')).toEqual(true)
  expect(isStringJwt('not a JSON Web Token')).toEqual(false)
})
