import { expect, it } from 'vitest'
import { isStringFloat, isStringFloatNegative, isStringFloatPositive, isStringInteger, isStringIntegerNegative, isStringIntegerPositive, isStringNumber } from './isStringNumber'

it('should return true if value is a number as a string', () => {
  expect(isStringNumber('123')).toEqual(true)
  expect(isStringNumber('-123')).toEqual(true)
  expect(isStringNumber('0')).toEqual(true)
  expect(isStringNumber('0.1')).toEqual(true)
  expect(isStringNumber('-0.1')).toEqual(true)
  expect(isStringNumber('1e5')).toEqual(true)
  expect(isStringNumber('-1e5')).toEqual(true)
  expect(isStringNumber('1e-5')).toEqual(true)
  expect(isStringNumber('-1e-5')).toEqual(true)
  expect(isStringNumber('1.1e5')).toEqual(true)
  expect(isStringNumber('-1.1e5')).toEqual(true)
  expect(isStringNumber('1.1e-5')).toEqual(true)
  expect(isStringNumber('-1.1e-5')).toEqual(true)
  expect(isStringNumber('foo')).toEqual(false)
  expect(isStringNumber('1foo')).toEqual(false)
  expect(isStringNumber('foo1')).toEqual(false)
})

it('should return true if value is an integer as a string', () => {
  expect(isStringInteger('123')).toEqual(true)
  expect(isStringInteger('-123')).toEqual(true)
  expect(isStringInteger('0')).toEqual(true)
  expect(isStringInteger('0.1')).toEqual(false)
  expect(isStringInteger('-0.1')).toEqual(false)
  expect(isStringInteger('1e5')).toEqual(false)
  expect(isStringInteger('-1e5')).toEqual(false)
  expect(isStringInteger('foo')).toEqual(false)
  expect(isStringInteger('1foo')).toEqual(false)
  expect(isStringInteger('foo1')).toEqual(false)
})

it('should return true if value is a positive integer as a string', () => {
  expect(isStringIntegerPositive('123')).toEqual(true)
  expect(isStringIntegerPositive('-123')).toEqual(false)
  expect(isStringIntegerPositive('0')).toEqual(true)
  expect(isStringIntegerPositive('0.1')).toEqual(false)
  expect(isStringIntegerPositive('-0.1')).toEqual(false)
  expect(isStringIntegerPositive('1e5')).toEqual(false)
  expect(isStringIntegerPositive('-1e5')).toEqual(false)
  expect(isStringIntegerPositive('foo')).toEqual(false)
  expect(isStringIntegerPositive('1foo')).toEqual(false)
  expect(isStringIntegerPositive('foo1')).toEqual(false)
})

it('should return true if value is a negative integer as a string', () => {
  expect(isStringIntegerNegative('123')).toEqual(false)
  expect(isStringIntegerNegative('-123')).toEqual(true)
  expect(isStringIntegerNegative('0')).toEqual(false)
  expect(isStringIntegerNegative('0.1')).toEqual(false)
  expect(isStringIntegerNegative('-0.1')).toEqual(false)
  expect(isStringIntegerNegative('1e5')).toEqual(false)
  expect(isStringIntegerNegative('-1e5')).toEqual(false)
  expect(isStringIntegerNegative('foo')).toEqual(false)
  expect(isStringIntegerNegative('1foo')).toEqual(false)
  expect(isStringIntegerNegative('foo1')).toEqual(false)
})

it('should return true if value is an float as a string', () => {
  expect(isStringFloat('123')).toEqual(true)
  expect(isStringFloat('-123')).toEqual(true)
  expect(isStringFloat('0')).toEqual(true)
  expect(isStringFloat('0.1')).toEqual(true)
  expect(isStringFloat('-0.1')).toEqual(true)
  expect(isStringFloat('1e5')).toEqual(false)
  expect(isStringFloat('-1e5')).toEqual(false)
  expect(isStringFloat('foo')).toEqual(false)
  expect(isStringFloat('1foo')).toEqual(false)
  expect(isStringFloat('foo1')).toEqual(false)
})

it('should return true if value is a positive float as a string', () => {
  expect(isStringFloatPositive('123')).toEqual(true)
  expect(isStringFloatPositive('-123')).toEqual(false)
  expect(isStringFloatPositive('0')).toEqual(true)
  expect(isStringFloatPositive('0.1')).toEqual(true)
  expect(isStringFloatPositive('-0.1')).toEqual(false)
  expect(isStringFloatPositive('1e5')).toEqual(false)
  expect(isStringFloatPositive('-1e5')).toEqual(false)
  expect(isStringFloatPositive('foo')).toEqual(false)
  expect(isStringFloatPositive('1foo')).toEqual(false)
  expect(isStringFloatPositive('foo1')).toEqual(false)
})

it('should return true if value is a negative float as a string', () => {
  expect(isStringFloatNegative('123')).toEqual(false)
  expect(isStringFloatNegative('-123')).toEqual(true)
  expect(isStringFloatNegative('0')).toEqual(false)
  expect(isStringFloatNegative('0.1')).toEqual(false)
  expect(isStringFloatNegative('-0.1')).toEqual(true)
  expect(isStringFloatNegative('1e5')).toEqual(false)
  expect(isStringFloatNegative('-1e5')).toEqual(false)
  expect(isStringFloatNegative('foo')).toEqual(false)
  expect(isStringFloatNegative('1foo')).toEqual(false)
  expect(isStringFloatNegative('foo1')).toEqual(false)
})
