name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  ci:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 16, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      # Install environment and dependencies
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install

      # Run tests
      - run: pnpm lint
      - run: pnpm test

      # Publish dev version to NPM
      # - run: pnpm version "$(jq -r '.version' package.json)-$(git rev-parse HEAD)"
      # - run: pnpm recursive publish --tag dev --access public
