name: CI
permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
    paths: 
      - "packages/**"
      - "scripts/**"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration & Deployment to Private Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          registry-url: "https://npm.hsjm.dev"

      # --- Install, build, and test.
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint:ci
      - run: pnpm test:ci

      # --- Publish to private registry on main branch.
      - if: github.event_name == 'push'
        run: pnpm publish:ci --registry https://npm.hsjm.dev --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PRIVATE}}
