name: Continuous Integration

permissions:
  id-token: write
  contents: write

on:
  push:
    tags:
      - v*
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next
  merge_group: {}

jobs:
  ci:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        node: [18.x]
        os: [ubuntu-latest]
        # node: [18.x, 16.x, 14.x]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

      # Set up Node.js and PNPM
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      # Run tests and lint
      - run: pnpm install
      # - run: pnpm lint # Disabled until linting issues are resolved
      - run: pnpm test:ci

      # Publish to NPM
      - name: Publish development version to NPM
        if: github.ref == 'refs/heads/main' && matrix.node == 18
        run: pnpm publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
          NODE_OPTIONS: --max-old-space-size=6144
